# application.yml 
--- 
spring: 
  application: 
    name: recensioni-seguite
  datasource:
    url: jdbc:postgresql://recensioniseguite-db:5432/recensioniseguite
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties.spring.json.trusted.packages: asw.goodbooks.*
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  cloud:
    loadbalancer: 
      ribbon.enabled: false 

server: 
# port: ${PORT:${SERVER_PORT:0}}
  port: 8080

# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false